{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-emulator-control",
    "version": "31.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.4.0.jar",
          "url": "android-test-plugin-host-emulator-control-31.4.0.jar",
          "size": 22567,
          "sha512": "0a145a19fbbb11cec95008b4a73328e8c05aa263affeec0f504bd73db12b884db95feeb68f498616ef7f70d9b354d1a9ec2bc189148985ac43263428baf67ec8",
          "sha256": "e805505739a07d9601c0056da56961d7c094e363e2c2181cd6549a9709cf17e3",
          "sha1": "060fc01442832fd7bd841bc7edb790675b09ab7b",
          "md5": "f556c909dee3020d21bc38b63e99e095"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-emulator-control-proto",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.emulator",
          "module": "proto",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-driver-instrumentation",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.4.0.jar",
          "url": "android-test-plugin-host-emulator-control-31.4.0.jar",
          "size": 22567,
          "sha512": "0a145a19fbbb11cec95008b4a73328e8c05aa263affeec0f504bd73db12b884db95feeb68f498616ef7f70d9b354d1a9ec2bc189148985ac43263428baf67ec8",
          "sha256": "e805505739a07d9601c0056da56961d7c094e363e2c2181cd6549a9709cf17e3",
          "sha1": "060fc01442832fd7bd841bc7edb790675b09ab7b",
          "md5": "f556c909dee3020d21bc38b63e99e095"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.4.0-javadoc.jar",
          "url": "android-test-plugin-host-emulator-control-31.4.0-javadoc.jar",
          "size": 261,
          "sha512": "96bc8ceed7617c289b4b3769fa6298c32ad948e9095c44b5344a81345f86c90ce1320685c6386d1ac81a31ddf8403bff3612ff15ebd3fd451a1753524f4ffe62",
          "sha256": "44a249d40ee3095cfbd1c339035261444a23de04639de3ea710ac67ec87f5ee7",
          "sha1": "37b94cbfd7b8b096a30c2964a1fe55b007a12ef2",
          "md5": "0f755c8dc425053c1ddd9679caefa08c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-emulator-control-31.4.0-sources.jar",
          "url": "android-test-plugin-host-emulator-control-31.4.0-sources.jar",
          "size": 8383,
          "sha512": "96dd76f335c957c3699c5e67813a5e7d4baa828bcf40d870c9ef7a96ca833f9439f528da0f81d38961d43eb848f88f8d7989e4c7dc94f35691e0d3ecf78f17a3",
          "sha256": "b5fadd06988dc473d420d6577ed74f87a793ff730a8195aeeedf107aa0bdb4cd",
          "sha1": "e82fddad1fb5610f6a013461a9d9081c875786ba",
          "md5": "3e867634dec97bb835ddfefac05228c9"
        }
      ]
    }
  ]
}
