{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "8.4.0-11315950",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-8.4.0-11315950.jar",
          "url": "aapt2-proto-8.4.0-11315950.jar",
          "size": 712652,
          "sha512": "a2d98599b20504ac10e63df133fd59efa84be62edf357229f0a34616dc34d4d2b5d7152dae5959de72e1d2b1106ac1e2a65ae523b3a2909bf733d090994e9ca0",
          "sha256": "f2832942e1de78a4544d671850d35e4b6e9b0342c1dc216c081707fb98b0dfbe",
          "sha1": "d0b137e4b167fa759062c4dd72f9d7f26c3470a1",
          "md5": "aa40a81ccbedd15dad6b923d6c8ecc2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-8.4.0-11315950.jar",
          "url": "aapt2-proto-8.4.0-11315950.jar",
          "size": 712652,
          "sha512": "a2d98599b20504ac10e63df133fd59efa84be62edf357229f0a34616dc34d4d2b5d7152dae5959de72e1d2b1106ac1e2a65ae523b3a2909bf733d090994e9ca0",
          "sha256": "f2832942e1de78a4544d671850d35e4b6e9b0342c1dc216c081707fb98b0dfbe",
          "sha1": "d0b137e4b167fa759062c4dd72f9d7f26c3470a1",
          "md5": "aa40a81ccbedd15dad6b923d6c8ecc2a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.4.0-11315950-javadoc.jar",
          "url": "aapt2-proto-8.4.0-11315950-javadoc.jar",
          "size": 1063962,
          "sha512": "cd590a9c1b0f5ad4aecba425e3c3fbba83372b380eab06ec02cce6af83e9e3efc8287be5f9ac914a38a2054268cb700476648062ef94bd02698c991c30616cd8",
          "sha256": "0ad222875d9a3503088f541076179ab0d6b64684cd5ab6232ae46951fba8bc69",
          "sha1": "b5217dfcf1753967eed8eb0d9722b2c3ce157983",
          "md5": "0037cdecd419bcc53441e7bcbcc20ce1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.4.0-11315950-sources.jar",
          "url": "aapt2-proto-8.4.0-11315950-sources.jar",
          "size": 396230,
          "sha512": "b3bd590f6630925d99b61abd444465d868ba0a78ef1f4cc92e6b0116ed2789d24ab3f2d7d407012ecc2489c135d0650798fb73b57a5f997adae4fc01b3220357",
          "sha256": "41d1064d7f8c602c72ced627d2a61f0c80c20990d1d3787078c47a830398efa9",
          "sha1": "fd353f9c4dff1ddbb0b1e665e697a63c30d4d171",
          "md5": "cc5cb68c2f7265a2e8ec679b098f7aed"
        }
      ]
    }
  ]
}
