{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.0.jar",
          "url": "gradle-settings-api-8.4.0.jar",
          "size": 9856,
          "sha512": "96ffdc2289796b9aabe2a745a825fe55024274cd90589f3dbcac671e1f1c48418781ed5c5589ce82d57efe113647b0a687e7243fb586db386180f1f041dc62b5",
          "sha256": "d9f43bf45b8e642803997216012236baa076574cafb89cd95a315ac7c38ea8e6",
          "sha1": "2e95d4817e1a2982dd77123fccc76ff257674ad0",
          "md5": "3a2e673360f850b226e8d6ff08ae79a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.4.0.jar",
          "url": "gradle-settings-api-8.4.0.jar",
          "size": 9856,
          "sha512": "96ffdc2289796b9aabe2a745a825fe55024274cd90589f3dbcac671e1f1c48418781ed5c5589ce82d57efe113647b0a687e7243fb586db386180f1f041dc62b5",
          "sha256": "d9f43bf45b8e642803997216012236baa076574cafb89cd95a315ac7c38ea8e6",
          "sha1": "2e95d4817e1a2982dd77123fccc76ff257674ad0",
          "md5": "3a2e673360f850b226e8d6ff08ae79a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.0-javadoc.jar",
          "url": "gradle-settings-api-8.4.0-javadoc.jar",
          "size": 261,
          "sha512": "185e43c6630292bd94a007bf700fab8c3cfd18fa0e5afa473d9ee30cd4cfa96333189fc2575d2937f4074527b3fd5bdfb8bbe598007b92ad8d1f5b09ec568ec9",
          "sha256": "61394664c8b7d2cb9d8e004417dac8b6450e893ffb95141afa308e95444d92c0",
          "sha1": "300ca9b3793fc655babab2270cb037f4cd27f1ed",
          "md5": "d508ac81d119ba50ceda3decc67f3b07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.0-sources.jar",
          "url": "gradle-settings-api-8.4.0-sources.jar",
          "size": 9407,
          "sha512": "56f622f528fd0707bf96312f85896c3716b4b5f12bdd75201efb156be63963d68471db95d67f44fc85b2695b26c63fd692247f7ebeb0132919d372f7090b277f",
          "sha256": "7e16348e11180efce8906886905ae9531b178bf75eb602abd9ae90fffffa51fb",
          "sha1": "3304ef330e6231f6d32da5a91b5e9418cff920f8",
          "md5": "4183e6db437e9b10cebbfb6adad37cb9"
        }
      ]
    }
  ]
}
