{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-ddmlib",
    "version": "31.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.4.0.jar",
          "url": "android-device-provider-ddmlib-31.4.0.jar",
          "size": 59673,
          "sha512": "ad11378cb360ea3b57218e68881c4325ab72d88cd20b29e19c20ecaecd28b3bf1b062fb8fa085efc42d1dbc6726d64632b530c301afb262e52fd1b8abbfe8fee",
          "sha256": "fd1cf6b06e1743896944ce545874258e2b6dfc5519db4dceb091aff6c7c2d37a",
          "sha1": "e97536c4e29518bf80b02a9cd405f192fee1b9f3",
          "md5": "71aafc1ac2f01c784ea16776cc437638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.4.0.jar",
          "url": "android-device-provider-ddmlib-31.4.0.jar",
          "size": 59673,
          "sha512": "ad11378cb360ea3b57218e68881c4325ab72d88cd20b29e19c20ecaecd28b3bf1b062fb8fa085efc42d1dbc6726d64632b530c301afb262e52fd1b8abbfe8fee",
          "sha256": "fd1cf6b06e1743896944ce545874258e2b6dfc5519db4dceb091aff6c7c2d37a",
          "sha1": "e97536c4e29518bf80b02a9cd405f192fee1b9f3",
          "md5": "71aafc1ac2f01c784ea16776cc437638"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.4.0-javadoc.jar",
          "url": "android-device-provider-ddmlib-31.4.0-javadoc.jar",
          "size": 261,
          "sha512": "9088be19ca3544e91870c516d5ef1ea76194facb936e904cd6bff60e4a2230572717b8e2bac1254e3b02b2da0e53c13ba555a990e459d42dd7613b84b438fb87",
          "sha256": "d17de813071db93d32d75d0742fdd91159618aa388263ff831b0f2f915105964",
          "sha1": "66b5bbcda1649a1028e2832ea25e99925bdfc9ad",
          "md5": "150085b53093334ac7e98530ab336c63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.4.0-sources.jar",
          "url": "android-device-provider-ddmlib-31.4.0-sources.jar",
          "size": 10987,
          "sha512": "f4f08019e0fbc6a1851097502134865cb8cd9390edb38c90439c192c0fb002bad2ad25909846e32c5a50fd9b1a0b33d011e575e864b67837c46e2687d411ddb7",
          "sha256": "ff69440c29b8c888dd59f01855ab6db0bb441b1ff0b7b5e1ff45278a5f1becd5",
          "sha1": "ab66f49c83a4f9fc2e5cf8fc1d75e5544f93f886",
          "md5": "b7d5cf0a47e940be70758eeeb795f9eb"
        }
      ]
    }
  ]
}
