{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.4.0.jar",
          "url": "manifest-merger-31.4.0.jar",
          "size": 246091,
          "sha512": "9df591feb57a3d5ef9e41c0c5c18c65c7a4f3dac29b92248f753b65231154b756a20a8ebc8b7a9ebb866d784664a0b7030dc7ed95e900ae02a9e76911bc32885",
          "sha256": "3439ddad91cf62aa5617af1c3ac2849e35878b487e972dfda26f07236a07e031",
          "sha1": "c9b06c6a8b1dee31c38f723f572c8e2d40e29ac2",
          "md5": "2e6ba7f12f53b36c6b6dc41ea9372583"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.4.0.jar",
          "url": "manifest-merger-31.4.0.jar",
          "size": 246091,
          "sha512": "9df591feb57a3d5ef9e41c0c5c18c65c7a4f3dac29b92248f753b65231154b756a20a8ebc8b7a9ebb866d784664a0b7030dc7ed95e900ae02a9e76911bc32885",
          "sha256": "3439ddad91cf62aa5617af1c3ac2849e35878b487e972dfda26f07236a07e031",
          "sha1": "c9b06c6a8b1dee31c38f723f572c8e2d40e29ac2",
          "md5": "2e6ba7f12f53b36c6b6dc41ea9372583"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.4.0-javadoc.jar",
          "url": "manifest-merger-31.4.0-javadoc.jar",
          "size": 274805,
          "sha512": "e9e992f478c165e04d45339c8f7c483fe870d4a6cd4c7d0648acb1a2b80755a774d6219470579b44c0007161ee763b254db9f7cb7c0ce52c47040ce9f04d6bf4",
          "sha256": "caa928b0a9222941fe23e7202c717630d039ad2a3c8284d74c953443c16541b7",
          "sha1": "cbd32b38588121a1328a2c6d16d0797f3e40df75",
          "md5": "5c8536697699fd5954723c0cc48586fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.4.0-sources.jar",
          "url": "manifest-merger-31.4.0-sources.jar",
          "size": 230106,
          "sha512": "9db5af9f96edaa8fe15b6fe0d99e5620a960ab1ea02d15b1441d535fd315e6c66202993af0219b875fc3fdc1e0deb57ce9004952813d77df67487013e8ff0b9c",
          "sha256": "ca146ed7e02c503ade8cde6439ba4eaab7596b336112eeba18063aa9ccadae60",
          "sha1": "82f4eeaa9c04337996c181171993b58131a3b304",
          "md5": "d5e97addac4b7290c1c8d53bc878a387"
        }
      ]
    }
  ]
}
