{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-additional-test-output",
    "version": "31.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.4.0.jar",
          "url": "android-test-plugin-host-additional-test-output-31.4.0.jar",
          "size": 16790,
          "sha512": "4d00566f3c7c5e4ff5d9cad752c985bb4d5b23b7676dae37287cfabd39b56c3a8621745e8d7a41f3b1cdbef45a5bf0b80575b5290206af8e93a160b45289bb66",
          "sha256": "fba57197622753863fdf9b2042518d47e9f9e44eddc315ddfd99d75eb8db044f",
          "sha1": "28a2275eef16f273790c3a6d13a6734e4dbe09b2",
          "md5": "a2ec4f97d1a72154b11a5da8f3105ea5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.4.0.jar",
          "url": "android-test-plugin-host-additional-test-output-31.4.0.jar",
          "size": 16790,
          "sha512": "4d00566f3c7c5e4ff5d9cad752c985bb4d5b23b7676dae37287cfabd39b56c3a8621745e8d7a41f3b1cdbef45a5bf0b80575b5290206af8e93a160b45289bb66",
          "sha256": "fba57197622753863fdf9b2042518d47e9f9e44eddc315ddfd99d75eb8db044f",
          "sha1": "28a2275eef16f273790c3a6d13a6734e4dbe09b2",
          "md5": "a2ec4f97d1a72154b11a5da8f3105ea5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.4.0-javadoc.jar",
          "url": "android-test-plugin-host-additional-test-output-31.4.0-javadoc.jar",
          "size": 261,
          "sha512": "825f2a21b40330a5097adf09988ac75420ea38ba28a36d9a23eb49246b3df9935fc7915b4646c573ac613f2eb998b9269c581c3f19418a1b88f0776e51f91cf0",
          "sha256": "fe78db3f73b45d2d79af404da147aa395ffb24770a012aa02057e8ede05999ed",
          "sha1": "1115d0a59488dd2ca2fa347bf06f7561e949ddc2",
          "md5": "de33ea3f5734bb7b4cf17901e979b4c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.4.0-sources.jar",
          "url": "android-test-plugin-host-additional-test-output-31.4.0-sources.jar",
          "size": 5516,
          "sha512": "1d9d8c4e07f5f992dbed203de76cad0a9e0cd31e7de826662f968756ce33ccfa6f6adae9818f25aeee13423d49b5d0604b844c0d70f23a8eaa81b90965209329",
          "sha256": "c747b5e4b2c6c88208a657b6b8fb6105f8425201b4a45e713c4d175ed2494eec",
          "sha1": "3f2bd2322cb24fd1d2463a56a784dc31d805b261",
          "md5": "0a428f4e2b6abedab95bf4f7e40abd7b"
        }
      ]
    }
  ]
}
