{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.4.0.jar",
          "url": "builder-model-8.4.0.jar",
          "size": 122814,
          "sha512": "60a1b103156ad90d6061a553b8069b47094ec99dc1a3df3dcf71366a8b35763ee4b81ebc801ea4436796a4213ec58a95ec22771274f3df19612beb6e30febd17",
          "sha256": "0ad5a52ef979140c3ddeab546c0c7e5abf02b8fbf5f8a2fbffeee54ef3eac39d",
          "sha1": "2ce5cd3c4157436ca795b20b26580bf6d932758d",
          "md5": "9de9715384868f38f0a883376040fd41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.4.0.jar",
          "url": "builder-model-8.4.0.jar",
          "size": 122814,
          "sha512": "60a1b103156ad90d6061a553b8069b47094ec99dc1a3df3dcf71366a8b35763ee4b81ebc801ea4436796a4213ec58a95ec22771274f3df19612beb6e30febd17",
          "sha256": "0ad5a52ef979140c3ddeab546c0c7e5abf02b8fbf5f8a2fbffeee54ef3eac39d",
          "sha1": "2ce5cd3c4157436ca795b20b26580bf6d932758d",
          "md5": "9de9715384868f38f0a883376040fd41"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.4.0-javadoc.jar",
          "url": "builder-model-8.4.0-javadoc.jar",
          "size": 291474,
          "sha512": "6192581d28f3403a1237f79dd90f80b0889935dc4aab6051f6c5b3070308586a6edc5b2d5832640fa89d8668fcaef5f124f0e3aa8b043502ee9f6d76f473f3d6",
          "sha256": "57d02d9ce8914156d132d02410a15167a82d4bddd80eb1d69fb5fe04ad4f8415",
          "sha1": "1d76907a20cfa2431d49993db71a84e8413cd7ce",
          "md5": "924a509c44cc2a59269875041e6cc717"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.4.0-sources.jar",
          "url": "builder-model-8.4.0-sources.jar",
          "size": 143166,
          "sha512": "c09fc5656d4c3ee755359a85f8c6ef30fd8abf42a682b062cc358e0f7679a3fb72a8d4cc3b556cefdf16b74e7ce5980935145b0086d2216d6074c73343aadbc2",
          "sha256": "02a227e35b20c32a37e4134193d207db275404581e86dad2e2cf5f16c4ed7c6d",
          "sha1": "e46c8a3346a62e1409e8501eb729b62cb1a9edd8",
          "md5": "43cb05e21576a46154e903fa7506536c"
        }
      ]
    }
  ]
}
