{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-apk-installer",
    "version": "31.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.4.0.jar",
          "url": "android-test-plugin-host-apk-installer-31.4.0.jar",
          "size": 20069,
          "sha512": "27b7be0c8cf9706236946c8fa05f08f7a25a40f7b99796150229b6fa48a845194ad055ea35e1a469abf5ea01d420a2450614245b3fee7f0d4081a9da92105417",
          "sha256": "39642d001acffc5a131f389ce2997f3e0f23c1e31fea292107c8cd5d267f024b",
          "sha1": "c7ae3011f8be35d4578e6d928207c2387bf73628",
          "md5": "59dbea24207361a37f4431325b10081b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-apk-installer-proto",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.4.0.jar",
          "url": "android-test-plugin-host-apk-installer-31.4.0.jar",
          "size": 20069,
          "sha512": "27b7be0c8cf9706236946c8fa05f08f7a25a40f7b99796150229b6fa48a845194ad055ea35e1a469abf5ea01d420a2450614245b3fee7f0d4081a9da92105417",
          "sha256": "39642d001acffc5a131f389ce2997f3e0f23c1e31fea292107c8cd5d267f024b",
          "sha1": "c7ae3011f8be35d4578e6d928207c2387bf73628",
          "md5": "59dbea24207361a37f4431325b10081b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.4.0-javadoc.jar",
          "url": "android-test-plugin-host-apk-installer-31.4.0-javadoc.jar",
          "size": 261,
          "sha512": "825f2a21b40330a5097adf09988ac75420ea38ba28a36d9a23eb49246b3df9935fc7915b4646c573ac613f2eb998b9269c581c3f19418a1b88f0776e51f91cf0",
          "sha256": "fe78db3f73b45d2d79af404da147aa395ffb24770a012aa02057e8ede05999ed",
          "sha1": "1115d0a59488dd2ca2fa347bf06f7561e949ddc2",
          "md5": "de33ea3f5734bb7b4cf17901e979b4c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-apk-installer-31.4.0-sources.jar",
          "url": "android-test-plugin-host-apk-installer-31.4.0-sources.jar",
          "size": 5797,
          "sha512": "b496e3274078122d70a83e91be925dee35ecbc4289b6a1c270c4fe14a7c27c9e6aceae5cc2d9027895f61efcd9620fd59ec8781a724f7c06f6562d815cecd1d9",
          "sha256": "9107dac02b28c8e1cf046cbbd952b3c2b57ee7b8d114fa54c9dca6dd8ddf39cc",
          "sha1": "06df5a3f745bd3df6fb2b5b54ed8a26a371fd5dd",
          "md5": "9a368dfc012ca56b924cfe8d40dee49c"
        }
      ]
    }
  ]
}
