{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.4.0.jar",
          "url": "aaptcompiler-8.4.0.jar",
          "size": 499315,
          "sha512": "00d00f4f1ba8f3e370dfb5065fdd6f0bad959478e809afd998dacf17a701943e0c61289a7036b7b3b51e8e2903f2c641a90c2654db8a440518e93d08ba720ac9",
          "sha256": "bef2f718a07a2bf5affcf54bccd94dc7a8fdd4042772cd89719b377a2972e189",
          "sha1": "5f732fe633f7f425930f1f187fd343813698fb0a",
          "md5": "cbe29ecaad7cf44e90b8053bdd00822a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.4.0-11315950"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.4.0.jar",
          "url": "aaptcompiler-8.4.0.jar",
          "size": 499315,
          "sha512": "00d00f4f1ba8f3e370dfb5065fdd6f0bad959478e809afd998dacf17a701943e0c61289a7036b7b3b51e8e2903f2c641a90c2654db8a440518e93d08ba720ac9",
          "sha256": "bef2f718a07a2bf5affcf54bccd94dc7a8fdd4042772cd89719b377a2972e189",
          "sha1": "5f732fe633f7f425930f1f187fd343813698fb0a",
          "md5": "cbe29ecaad7cf44e90b8053bdd00822a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.4.0-javadoc.jar",
          "url": "aaptcompiler-8.4.0-javadoc.jar",
          "size": 81065,
          "sha512": "b2dee12ac7af8bfb0cbabb2e8fa6c13a8b70065dc20694d05beaada82f180938926fec2574c9ca9c482a495c582f14deaadcb71b7c1dbbabf17ab4d904ba8699",
          "sha256": "637bb9dfd38ed0e2302ad171180db160b92fb7ae786721000da9fef42862a396",
          "sha1": "acc5d23b1942366b6e1aa368359ff921e454a869",
          "md5": "29d95bf931d7434a200abc14f34b6c3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.4.0-sources.jar",
          "url": "aaptcompiler-8.4.0-sources.jar",
          "size": 152981,
          "sha512": "95dbf4c22abad730cc5de1cc8e4a8a8b3ce4a78892363f96ddf7ab37eb4a045fe2072c8418a572ca36b34e853c27077086fab86395aa242147d90b519532ccf1",
          "sha256": "e5efe82ed7006b75a3c53d3d0e003b30f3882d96fbc5cb97210a5277de0f0bd6",
          "sha1": "3cdb3446b95b23c845b6c99d97d122977fe9a379",
          "md5": "06d260c3a8938cfd5e2ac7ab5f601f7b"
        }
      ]
    }
  ]
}
