{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-device-info",
    "version": "31.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.4.0.jar",
          "url": "android-test-plugin-host-device-info-31.4.0.jar",
          "size": 10547,
          "sha512": "e5ec37d3064c2bcaf9f9b6d6812fe2e90797649698a38ed64d141fe543a54eb06acc8d9039f1a24194f1b13051e538073040719553e628f5eef7de538434b59a",
          "sha256": "4caffd2c254737596dbd3a56a138a691f668b21d8b2e882488d1dcac3e366c7f",
          "sha1": "82f7a7b4204638d8c90aba84ef03da02e0345721",
          "md5": "86848b90fdce3136cbd27c9906ba10c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-device-info-proto",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.4.0.jar",
          "url": "android-test-plugin-host-device-info-31.4.0.jar",
          "size": 10547,
          "sha512": "e5ec37d3064c2bcaf9f9b6d6812fe2e90797649698a38ed64d141fe543a54eb06acc8d9039f1a24194f1b13051e538073040719553e628f5eef7de538434b59a",
          "sha256": "4caffd2c254737596dbd3a56a138a691f668b21d8b2e882488d1dcac3e366c7f",
          "sha1": "82f7a7b4204638d8c90aba84ef03da02e0345721",
          "md5": "86848b90fdce3136cbd27c9906ba10c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.4.0-javadoc.jar",
          "url": "android-test-plugin-host-device-info-31.4.0-javadoc.jar",
          "size": 261,
          "sha512": "cf2f77e4fd040e0ba07d8d332b98f4bbead84375b5f595d29e3791aa3862884011ebf6e0d97c3c5345243fd2cd89cc5fbbb10bfca6d57909b15b3efd94698998",
          "sha256": "e5cca90787ffc0d128a5140733782eab3e9ea941843b327a3fdec92231e64f01",
          "sha1": "01f18d75c7f1db64c9571b021b44290208488d84",
          "md5": "20c370bec9ef04f5c6677787262eb9aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.4.0-sources.jar",
          "url": "android-test-plugin-host-device-info-31.4.0-sources.jar",
          "size": 4397,
          "sha512": "268babfd417936b8d12a8692cf9ff1428939a5028ead62c98f7b77017de96d7f509a4c4ecd653f3e8e719a1c40ed146541a12011cbf5fb50bb26f85b43cdd95c",
          "sha256": "c27f748d4315571eee487448915b9d82df1059e5e7ae1dcaec8ff7a84a08a81d",
          "sha1": "dac29d368dfad1e881ef4b01f9d9d5e0efdb0e3d",
          "md5": "1db5c7cf0c1a5ea92386b464b6320b40"
        }
      ]
    }
  ]
}
