{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cucumber",
    "module": "cucumber-android",
    "version": "7.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.cucumber",
          "module": "cucumber-java",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "io.cucumber",
          "module": "cucumber-junit",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "cucumber-android-7.14.0.aar",
          "url": "cucumber-android-7.14.0.aar",
          "size": 71027,
          "sha512": "9c8d830fd03b84ccb5fb5d3f29591019089ecc71aa197f9e2d94d2b2709fa988c4014a8e5b3677c7bd9e7b0dcf75d32f47837d18466f39cd0fa60ac94d0da71e",
          "sha256": "2e7d4d8ade8640035a3f14a50d12979dae82fea9780d22cddffc85c6de5a89dc",
          "sha1": "bffc223694f57b5147a550ad832ceb6e7adf4bae",
          "md5": "6208e958e7717174661dae65cc64591f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.cucumber",
          "module": "cucumber-junit-rules-support",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "io.cucumber",
          "module": "cucumber-java",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "io.cucumber",
          "module": "cucumber-junit",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "cucumber-android-7.14.0.aar",
          "url": "cucumber-android-7.14.0.aar",
          "size": 71027,
          "sha512": "9c8d830fd03b84ccb5fb5d3f29591019089ecc71aa197f9e2d94d2b2709fa988c4014a8e5b3677c7bd9e7b0dcf75d32f47837d18466f39cd0fa60ac94d0da71e",
          "sha256": "2e7d4d8ade8640035a3f14a50d12979dae82fea9780d22cddffc85c6de5a89dc",
          "sha1": "bffc223694f57b5147a550ad832ceb6e7adf4bae",
          "md5": "6208e958e7717174661dae65cc64591f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cucumber-android-7.14.0-sources.jar",
          "url": "cucumber-android-7.14.0-sources.jar",
          "size": 19037,
          "sha512": "e2eb7ea4b3d230a11b805a83a1fda815afb201e28e349e6fc3053d023cba7fcf71a8f76f9418ce801c15087c50b727638170877f177b92eef8973245122ed902",
          "sha256": "f674e178e6487608c0f60974b85c382e1af105051201c5d1a9aa06018459d826",
          "sha1": "996570afcceeb27cba9625baad0e2570cf91ac49",
          "md5": "7dec3503e3ae9a76903bf6c9d90fe5d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cucumber-android-7.14.0-javadoc.jar",
          "url": "cucumber-android-7.14.0-javadoc.jar",
          "size": 317700,
          "sha512": "f17d11224155be002e8aa99c85a070096378ee1e866fe2cd7b96d81b04b05029c18ef5b77c676b8d11d3ce35b9c1d0a49f1d2bf8d0658ea9219497590d2835ad",
          "sha256": "097f8c6c79cf04e82bfd223cf4f7be9aaf5817f54858ea8411d8faebac5ef4a4",
          "sha1": "687ea1dab282f8e847b921a3a3c755fceb53808c",
          "md5": "bc95d8fb42507593a70467b1f9c91f59"
        }
      ]
    }
  ]
}
