{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.arch.core",
    "module": "core-testing",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "2.25.0"
          },
          "excludes": [
            {
              "group": "net.bytebuddy",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-testing-2.2.0.aar",
          "url": "core-testing-2.2.0.aar",
          "size": 11812,
          "sha512": "8c55927106a51d7e67162be9974192a156d72de3b90285028f625221eb187015c095ef07e7d67edca064e101681cd811370aaf63fa24928327706d528034220a",
          "sha256": "85e1fe770ed673ecb8552eaadc23b96d8db0a14a10eaa7789518496e5d99362c",
          "sha1": "fa0035bc85ef4918ff47bfdadc3d7eb3ea74aa54",
          "md5": "6ac355da176ccb710566a1ffd7ab3390"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "2.25.0"
          },
          "excludes": [
            {
              "group": "net.bytebuddy",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-testing-2.2.0.aar",
          "url": "core-testing-2.2.0.aar",
          "size": 11812,
          "sha512": "8c55927106a51d7e67162be9974192a156d72de3b90285028f625221eb187015c095ef07e7d67edca064e101681cd811370aaf63fa24928327706d528034220a",
          "sha256": "85e1fe770ed673ecb8552eaadc23b96d8db0a14a10eaa7789518496e5d99362c",
          "sha1": "fa0035bc85ef4918ff47bfdadc3d7eb3ea74aa54",
          "md5": "6ac355da176ccb710566a1ffd7ab3390"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-testing-2.2.0-sources.jar",
          "url": "core-testing-2.2.0-sources.jar",
          "size": 6898,
          "sha512": "c425d1fdcf5aebb55ce5ce4277ca93a2cfd064f50156bb40d097d807d1c0671e52f1d51d1a990378c294a5582fcc73fe8433d26e704d9807cb97a84a1c69d573",
          "sha256": "0ded176aa10334727f36285385b28bf7cfd897dd49f3c841382b8bee2e2b7897",
          "sha1": "3e62766aa73bfefb3f504249858f213a02174452",
          "md5": "8a7e77ff1e4ef9b4aeea3ba664dd9940"
        }
      ]
    }
  ]
}