{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.4.0.jar",
          "url": "builder-test-api-8.4.0.jar",
          "size": 15329,
          "sha512": "a4defdb68770c5d83238969823a9806f3a0ee8e0ee952c5a27ff182a94391cfad2255f23a6d9aaaa805913471d556b49a11212453086e32bcb7cc27dcb9f059e",
          "sha256": "ab6c1db019eb72dc626a21fae555f44b2da7c0622ae730cd93846810cc1f532d",
          "sha1": "e49d832c8f2d4a769c19df8016572d30c756dd9c",
          "md5": "2d57c5e9ec361df14635c99b70780bb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.4.0.jar",
          "url": "builder-test-api-8.4.0.jar",
          "size": 15329,
          "sha512": "a4defdb68770c5d83238969823a9806f3a0ee8e0ee952c5a27ff182a94391cfad2255f23a6d9aaaa805913471d556b49a11212453086e32bcb7cc27dcb9f059e",
          "sha256": "ab6c1db019eb72dc626a21fae555f44b2da7c0622ae730cd93846810cc1f532d",
          "sha1": "e49d832c8f2d4a769c19df8016572d30c756dd9c",
          "md5": "2d57c5e9ec361df14635c99b70780bb5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.4.0-javadoc.jar",
          "url": "builder-test-api-8.4.0-javadoc.jar",
          "size": 117213,
          "sha512": "848875b41f65d389487fcb72f26796a29410902df3835866be3b777c5fd0702c2039848428a2415eefdd1c85ca355f798d6d0973559522b58c5cba1253aac156",
          "sha256": "7360ac7e0f88d3b26defb3f8b24da793dfe86d7b1b05534e376dfa3b2e643529",
          "sha1": "bec538a53671c7744953b8a9ac9fc4796575202b",
          "md5": "e084b85e9fd71a13cd3453519005331a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.4.0-sources.jar",
          "url": "builder-test-api-8.4.0-sources.jar",
          "size": 13848,
          "sha512": "0cf3d6e73875ae2c973d92eb5086f263c5360c45da3010047dd8b519c18b9b9bc11be688e62a326cc7f86a61590d73d49fe735d455a25dae82c25a3b033f92dc",
          "sha256": "0e6690e96177f516b7bac6b5ee3a1a8f9057ef6132608344a63ad9819e8e54fc",
          "sha1": "c1ebd99bad286d4251716e6a32ca1c399c7f7236",
          "md5": "8f99ec6f6e53ac17475cf183ab9f6fd9"
        }
      ]
    }
  ]
}
